import { describe, expect, it } from 'vitest';
import { inlineSponsorSvg } from './inlineSvg.ts';

/** Shaped like a real SponsorKit output, trimmed to the parts that matter. */
const SVG = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 800 448" width="800" height="448">
<!-- Generated by https://github.com/antfu-collective/sponsorkit -->
<style>
text {
  fill: #777777;
}
</style>
<text x="400" y="40" class="sponsorkit-tier-title">Sponsor</text>
<a href="https://github.com/Gallenkamp" class="sponsorkit-link" target="_blank" id="Gallenkamp">
<clipPath id="c0"><rect x="365" y="65" width="70" height="70" rx="35" ry="35" /></clipPath>
<image x="365" y="65" width="70" height="70" href="data:image/webp;base64,AAAA" clip-path="url(#c0)"/>
<text x="400" y="153" class="sponsorkit-name" fill="currentColor">Guido Gallenkamp</text>
</a>
</svg>`;

describe('inlineSponsorSvg', () => {
	it('keeps the viewBox but drops the fixed pixel size so CSS can scale it', () => {
		const out = inlineSponsorSvg(SVG);
		expect(out).toContain('viewBox="0 0 800 448"');
		expect(out).not.toContain('width="800"');
		expect(out).not.toContain('height="448"');
	});

	it('leaves the width/height of inner elements alone', () => {
		// Only the root <svg> is resized; the avatar images keep their geometry.
		expect(inlineSponsorSvg(SVG)).toContain('<image x="365" y="65" width="70" height="70"');
	});

	it('strips the internal style block that would otherwise leak document-wide', () => {
		const out = inlineSponsorSvg(SVG);
		expect(out).not.toContain('<style>');
		expect(out).not.toContain('#777777');
	});

	it('names the graphic as a whole', () => {
		expect(inlineSponsorSvg(SVG)).toContain('aria-label="VersaTiles sponsors"');
		expect(inlineSponsorSvg(SVG, 'Our backers')).toContain('aria-label="Our backers"');
	});

	it('gives each sponsor link an accessible name and rel=noopener', () => {
		const out = inlineSponsorSvg(SVG);
		expect(out).toContain('<a rel="noopener" aria-label="Gallenkamp" href=');
		expect(out).toContain('target="_blank"');
	});

	it('drops the link id, which would otherwise join the page id namespace', () => {
		const out = inlineSponsorSvg(SVG);
		expect(out).not.toContain('id="Gallenkamp"');
		// The label it carried survives on aria-label.
		expect(out).toContain('aria-label="Gallenkamp"');
	});

	it('namespaces the clip-path ids and keeps their references intact', () => {
		const out = inlineSponsorSvg(SVG);
		expect(out).toContain('id="sponsorkit-c0"');
		expect(out).toContain('clip-path="url(#sponsorkit-c0)"');
		// No bare generic id left to collide with the page.
		expect(out).not.toContain('id="c0"');
	});

	it('leaves every remaining id reachable from a url() reference', () => {
		const out = inlineSponsorSvg(SVG);
		const ids = [...out.matchAll(/\bid="([^"]*)"/g)].map((m) => m[1]);
		const refs = new Set([...out.matchAll(/url\(#([^)]*)\)/g)].map((m) => m[1]));
		expect(ids.length).toBeGreaterThan(0);
		expect(ids.filter((id) => !refs.has(id))).toEqual([]);
	});

	it('preserves the real destination rather than linking to our own page', () => {
		// The whole point of inlining: this href used to be unreachable.
		expect(inlineSponsorSvg(SVG)).toContain('href="https://github.com/Gallenkamp"');
	});

	it('escapes attribute-breaking characters in the label', () => {
		const out = inlineSponsorSvg(SVG, 'A "quoted" & <tagged> label');
		expect(out).toContain('aria-label="A &quot;quoted&quot; &amp; &lt;tagged&gt; label"');
	});

	it('strips an XML prolog', () => {
		const out = inlineSponsorSvg(`<?xml version="1.0" encoding="UTF-8"?>\n${SVG}`);
		expect(out.startsWith('<svg')).toBe(true);
	});

	it('is idempotent — a second pass adds no duplicate attributes', () => {
		const once = inlineSponsorSvg(SVG);
		expect(inlineSponsorSvg(once)).toBe(once);
	});

	it('does not touch a link that already carries rel and aria-label', () => {
		const svg =
			'<svg viewBox="0 0 1 1"><a rel="me" aria-label="Set" href="#" target="_blank">' +
			'</a></svg>';
		expect(inlineSponsorSvg(svg)).toContain('<a rel="me" aria-label="Set" href="#"');
	});

	it('handles an empty sponsor list without producing broken markup', () => {
		const out = inlineSponsorSvg('<svg viewBox="0 0 800 100" width="800" height="100"></svg>');
		expect(out).toBe('<svg aria-label="VersaTiles sponsors" viewBox="0 0 800 100"></svg>');
	});
});
